server.port=8080

spring.datasource.url=${DATABASE_USER_DB_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#spring.jpa.properties.hibernate.format_sql=true

jwt.algorithm=RS256
jwt.secret=${JWT_SECRET_KEY_PLAIN_TEXT}
jwt.private-key-path=${JWT_PRIVATE_KEY_PATH}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH}

auth.max-active-sessions=5

jwt-val.jwksUrl=${JWT_JWKS_URL}
jwt-val.algorithm=RS256

#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.transaction=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

# =======================
# Kafka Producer Config
# =======================

spring.kafka.bootstrap-servers=${EVENT_BROKER_URL}

# Producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Acknowledgement and reliability settings
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Performance tuning
spring.kafka.producer.batch-size=16384
spring.kafka.producer.linger-ms=5
spring.kafka.producer.buffer-memory=33554432

# Optional JSON Serializer config (to avoid adding type headers)
spring.kafka.properties.spring.json.add.type.headers=false

logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG